=== ario122/Distributed-Programming-II/dtd/flightInfo.dtd
<!ELEMENT flightmonitor (aircraft*, flight*, flightInstance*)>


<!ELEMENT aircraft (seat*)> 
<!ATTLIST aircraft
			model 				ID					#REQUIRED
			seatsNumber			CDATA				#REQUIRED
>		

<!ELEMENT seat EMPTY>
<!ATTLIST seat 
			number			CDATA			#REQUIRED
>

<!ELEMENT flight EMPTY>
<!ATTLIST flight
			number			ID				#REQUIRED
			from			CDATA			#REQUIRED
			to				CDATA			#REQUIRED
			time			CDATA			#REQUIRED
			
>

<!ELEMENT flightInstance (passenger*)>
<!ATTLIST flightInstance
			number		 	IDREF			#REQUIRED
			date			CDATA			#REQUIRED
			status			(BOOKING|ARRIVED|BOARDING|CANCELLED|CHECKINGIN|DEPARTED) 	#REQUIRED
			gate			CDATA			#REQUIRED
			delay			CDATA			#REQUIRED
			model			IDREF			#REQUIRED
>

<!ELEMENT passenger EMPTY>
<!ATTLIST passenger
			boarded			(true|false)			#REQUIRED
			name			CDATA					#REQUIRED
			seat			CDATA					#REQUIRED
>

=== ario122/Distributed-Programming-II/dtd/flight.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flightmonitor SYSTEM "flightInfo.dtd">
<flightmonitor>
	<aircraft model = "B747" seatsNumber = "200">
		<seat number = "14F" />
		<seat number = "14E" />
		<seat number = "14D" />
		<seat number = "14C" />
		<seat number = "14B" />
		<seat number = "14A" />
	</aircraft>
	<flight number = "XD1231" from = "TRN" to = "MXP" time = "10:00" />
	<flight number = "XD1235" from = "TRN" to = "MXP" time = "10:00" />
	
	
	<flightInstance number = "XD1235" date="11/02/2010 GMT" status="BOOKING" gate = "0" delay = "9" model = "B747">
		<passenger name= "mamad" seat = "13F" boarded = "true" />
		<passenger name= "mamad" seat = "13F" boarded = "true" />
		<passenger name= "mamad" seat = "13F" boarded = "true" />
		<passenger name= "mamad" seat = "13F" boarded = "true" />
		<passenger name= "mamad" seat = "13F" boarded = "true" />
	</flightInstance>
		
	<flightInstance number = "XD1231" date="11/02/2010 GMT" status="DEPARTED" gate = "3" delay = "29" model = "B747" />

	





</flightmonitor>
